'''
*************************************************************************************************
This is the fasttree_pipe.py script. It uses files generated by Roary to generate a
phylogenetic analysis.
It is called by UCT_WGS_pipeline.py.

(c) Dr GJK Marais 2023
**************************************************************************************************
'''
import os


def generate_fasttree_commands(roary_dict, output_dir):
    commands = []
    for org, analysis in roary_dict.items():
        command = ['fasttree', '-nt', '-gtr', '-gamma', analysis[1]]
        out = os.path.join(output_dir, f'{org}.newick')
        commands.append((command, out))
    return commands